### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by zanderwar**
Pet hate of popular repos missing packagist info :)

### CODE REVIEW

**Comment by nglasl** [comment]
I couldn't agree more with you on this :)

Have you tried clicking the heading?

https://github.com/nglasl/silverstripe-misdirection#misdirection

**Comment by zanderwar** [comment]
Ahh, your call on this one. No I had not tried clicking the heading ever in my 16 years of backend development experience ;P

I normally click the Packagist badge, or copy-paste the `composer require` line shown in 99% of repo's

Or read the composer.json and construct the packagist URL myself. Fun times.

I'm all for eliminating steps though

**Comment by nglasl** [comment]
Heh, yeah I agree that it could be improved. What do you think about having the first dot point under https://github.com/nglasl/silverstripe-misdirection/blob/master/README.md#getting-started linking to the packagist entry? While I do like having the explicit `composer require` example, this provides that and a little more (such as the framework version it depends on). I also like people knowing that packagist is a thing, rather than having a command that just magically pulls the module down :)

Thoughts?

**Comment by nglasl** [comment]
I had a little spare time between things today and I've pushed up the change that I suggested for this (and my other modules, because consistency). I'm going to close this for the time being, but please do let me know what you think. I'm hoping this makes the process smoother for you (and clear/concise for others that come along).

**Pull request closed without merging**
